### ISSUE TITLE
ERROR SENDING TO WEBHOOK on fslive

### ISSUE THREAD

**Issue by 7sharp9** [humhei/FCSWatch#38]
fscd: ERROR SENDING TO WEBHOOK: "System.Exception: error converting rhs of .ctor
System.Exception: NYI: extension of generic type, needs FCS support: IObservable`1::member Add

**Comment by 7sharp9** [comment]
This looks to be missing event/delegate support.

**Comment by 7sharp9** [comment]
full stack trace:
```
System.Exception: NYI: extension of generic type, needs FCS support: IObservable`1::member Add
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at FcsWatch.Porta.FromCompilerService.clo@245-35.Invoke(FSharpMemberOrFunctionOrValue arg20) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 245
   at FcsWatch.Porta.FromCompilerService.Convert.convMemberRef(FSharpMemberOrFunctionOrValue memb, range range) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 245
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 43
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.Convert.convExpr(FSharpExpr expr) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 110
   at FcsWatch.Porta.FromCompilerService.clo@341-44.GenerateNext(IEnumerable`1& next) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 358
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at FcsWatch.Porta.FromCompilerService.eR@358-3.Invoke(Exception arg20) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 358
   at FcsWatch.Porta.FromCompilerService.clo@341-44.GenerateNext(IEnumerable`1& next) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 358
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at FcsWatch.Porta.FromCompilerService.Convert.convDecl(FSharpImplementationFileDeclaration d) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 341
   at FcsWatch.Porta.FromCompilerService.clo@365-45.Invoke(FSharpImplementationFileDeclaration d) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 365
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at FcsWatch.Porta.FromCompilerService.Convert.convDecls(FSharpList`1 decls) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 365
   at FcsWatch.Porta.FromCompilerService.clo@341-44.GenerateNext(IEnumerable`1& next) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 344
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at FcsWatch.Porta.FromCompilerService.Convert.convDecl(FSharpImplementationFileDeclaration d) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 341
   at FcsWatch.Porta.FromCompilerService.clo@365-45.Invoke(FSharpImplementationFileDeclaration d) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 365
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at FcsWatch.Porta.FromCompilerService.Convert.convDecls(FSharpList`1 decls) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 365
   at FcsWatch.Porta.FromCompilerService.clo@341-44.GenerateNext(IEnumerable`1& next) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 344
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at FcsWatch.Porta.FromCompilerService.Convert.convDecl(FSharpImplementationFileDeclaration d) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 341
   at FcsWatch.Porta.FromCompilerService.clo@365-45.Invoke(FSharpImplementationFileDeclaration d) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 365
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at FcsWatch.Porta.FromCompilerService.Convert.convDecls(FSharpList`1 decls) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 365
   at FcsWatch.Porta.FromCompilerService.Convert.ConvertDecls(FSharpList`1 decls) in C:\projects\fcswatch\src\FcsWatch.Porta\FromCompilerService.fs:line 367
   at FcsWatch.Porta.FromProcessCommandLine.convFile(Boolean eval, FSharpImplementationFileContents i) in C:\projects\fcswatch\src\FcsWatch.Porta\FromProcessCommandLine.fs:line 17
   at FcsWatch.Porta.FromProcessCommandLine.data@20.Invoke(FSharpImplementationFileContents i) in C:\projects\fcswatch\src\FcsWatch.Porta\FromProcessCommandLine.fs:line 20
   at FcsWatch.Porta.FromProcessCommandLine.jsonFiles(Boolean eval, FSharpImplementationFileContents[] impls) in C:\projects\fcswatch\src\FcsWatch.Porta\FromProcessCommandLine.fs:line 20
   at FcsWatch.Porta.FromProcessCommandLine.sendToWebHook(Boolean eval, String hook, FSharpList`1 fileContents) in C:\projects\fcswatch\src\FcsWatch.Porta\FromProcessCommandLine.fs:line 27"
```
